# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
tokenizer_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_liger: true
bf16: true


# Dataset arguments
dataset_id_or_path: imdatta0/openthink_chat
max_seq_length: 20480
packing: true

# LoRA arguments
use_peft: false
load_in_4bit: false

# Training arguments
num_train_epochs: 1
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
max_grad_norm: 1.0
log_level: info
optim: "paged_adamw_32bit"

# Logging arguments
logging_strategy: steps
logging_steps: 16
eval_strategy: "steps"
eval_steps: 32
report_to:
- wandb
save_strategy: "steps"
save_steps: 32
seed: 3407

# Hugging Face Hub 
push_to_hub: true
hub_strategy: every_save


output_dir: /path/to/save_directory
hub_model_id: hf_model_name


#WANDB run args_med
run_name: wandb_run_name
# resume_from_checkpoint: